
public enum SodaScriptSkillCategory
{
	SPECIFIC=1,
    DEFAULT=2,
    STRONGEST_SELF_HEAL=3,
    STRONGEST_HEAL=4,
    STRONGEST_GROUP_HEAL=5,
    STRONGEST_ATTACK=6,
    STRONGEST_GROUP_ATTACK=7,
    ANY_NON_FRIENDLY_THAT_CONSUMES_MP=8,
    ANY_NON_FRIENDLY_THAT_DOESNT_CONSUME_MP=9,
    ANY=10,
    STRONGEST_SINGLE_TARGET_ATTACK=11,
    ANY_SELF_BUFF=12,
    ANY_BUFF=13,
    ANY_DEBUFF=14
}
