
public enum SpawnPatternId
{
    ONE_PLAYER, TWO_PLAYER, THREE_PLAYER, FOUR_PLAYER, FIVE_PLAYER, SIX_PLAYER,

    ONE_PLAYER_AMBUSHED, TWO_PLAYER_AMBUSHED, THREE_PLAYER_AMBUSHED, FOUR_PLAYER_AMBUSHED, FIVE_PLAYER_AMBUSHED, SIX_PLAYER_AMBUSHED,

    ONE_ENEMY, TWO_ENEMY, THREE_ENEMY, FOUR_ENEMY, FIVE_ENEMY, SEVEN_ENEMY,
    MINIBOSS, BOSS, DUNGEON_BOSS, TEMPERED_BOSS,
    
    TWO_ENEMY_AMBUSH, FOUR_ENEMY_AMBUSH, SIX_ENEMY_AMBUSH
}
